host: 127.0.0.1
port: 3000
revers: false
logs:
  format: '$name $ip $statusCode $statusMessage $method $forward_href $target_href'
  file: false
proxy:
  ws: true
  xfwd: false
  secure: false
  changeOrigin: true
  autoRewrite: true
ngrok:
  authtoken:
  region: us
routing:
  - active: true
    name: DEFAULT
    opts:
    forward: any
    target:
      default: https://httpbin.org
      rules:
    tunnel:
      active: false
      opts:
